## Este código prepara una CNN para probar un modelo usando datos locales

In [ ]:
#Conexión con Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

path='/content/drive/MyDrive/Colab Notebooks/Proyecto/prueba/prueba8.jfif'
img=image.load_img(path, target_size=(150, 150))
x=image.img_to_array(img)
image=np.expand_dims(x, axis=0)

In [ ]:
import json
a_file = open("/content/drive/MyDrive/Colab Notebooks/Proyecto/Modelo entrenado 2/fungi.json", "r")
#a_file = open("/content/drive/MyDrive/Colab Notebooks/Proyecto/fungi_indices.json", "r")
class_indices = json.load(a_file)
model = load_model('/content/drive/MyDrive/Colab Notebooks/Proyecto/Modelo entrenado 2/fungi_categorical.h5')
#model = load_model('/content/drive/MyDrive/Colab Notebooks/Proyecto/fungi_categorical.h5')
classes = model.predict(image)
print(classes)
clas =np.where(classes[0] == max(classes[0]))
categoria = clas[0][0]
print(categoria)
print(list(class_indices.keys())[list(class_indices.values()).index(categoria)])
type1= list(class_indices.keys())[list(class_indices.values()).index(categoria)]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
11
Suillus


In [ ]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
plt.imshow(img)
plt.title(type1) 
plt.show()

In [ ]:
def Inferencia (path):
  img=image.load_img(path, target_size=(150, 150))
  x=image.img_to_array(img)
  imagen=np.expand_dims(x, axis=0)
  import json
  #a_file = open("/content/drive/MyDrive/Colab Notebooks/Proyecto/Modelo entrenado 2/fungi.json", "r")
  a_file = open("/content/drive/MyDrive/Colab Notebooks/Proyecto/fungi_indices.json", "r")
  class_indices = json.load(a_file)
  #model = load_model('/content/drive/MyDrive/Colab Notebooks/Proyecto/Modelo entrenado 2/fungi_categorical.h5')
  model = load_model('/content/drive/MyDrive/Colab Notebooks/Proyecto/fungi_categorical.h5')
  classes = model.predict(imagen)
  print(classes)
  clas =np.where(classes[0] == max(classes[0]))
  categoria = clas[0][0]
  print(categoria)
  print(list(class_indices.keys())[list(class_indices.values()).index(categoria)])
  type1= list(class_indices.keys())[list(class_indices.values()).index(categoria)]

In [ ]:
Inferencia (path1)
Inferencia (path2)
Inferencia (path3)
Inferencia (path4)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
4
Entoloma
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
7
Inocybe
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
7
Inocybe
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
8
Lactarius
